// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./components/Board.vue')['default']
    Container: typeof import('./components/container.vue')['default']
    Painter: typeof import('./components/Painter.vue')['default']
    ToolBar: typeof import('./components/ToolBar.vue')['default']
  }
}

export { }
